In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.random.randint(1,5)

3

In [12]:
arr=np.arange(0,25)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 25 into shape (5,3)

In [16]:
arr=['a','b','c','d','e']

In [17]:
np.array(arr)

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [18]:
arr

['a', 'b', 'c', 'd', 'e']

In [19]:
arr=np.array(arr)

In [20]:
arr

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [21]:
arr.dtype

dtype('<U1')

In [25]:
arr=[1,2,3]

In [26]:
arr=np.array(arr)

In [27]:
arr

array([1, 2, 3])

In [3]:
np.arange(0,1,10)

array([0])

In [4]:
np.numarray(10)

TypeError: 'str' object is not callable

In [5]:
np.array_equal(10)

TypeError: _array_equal_dispatcher() missing 1 required positional argument: 'a2'

In [9]:
np.linspace(0,1,64).reshape(8,8)

array([[0.        , 0.01587302, 0.03174603, 0.04761905, 0.06349206,
        0.07936508, 0.0952381 , 0.11111111],
       [0.12698413, 0.14285714, 0.15873016, 0.17460317, 0.19047619,
        0.20634921, 0.22222222, 0.23809524],
       [0.25396825, 0.26984127, 0.28571429, 0.3015873 , 0.31746032,
        0.33333333, 0.34920635, 0.36507937],
       [0.38095238, 0.3968254 , 0.41269841, 0.42857143, 0.44444444,
        0.46031746, 0.47619048, 0.49206349],
       [0.50793651, 0.52380952, 0.53968254, 0.55555556, 0.57142857,
        0.58730159, 0.6031746 , 0.61904762],
       [0.63492063, 0.65079365, 0.66666667, 0.68253968, 0.6984127 ,
        0.71428571, 0.73015873, 0.74603175],
       [0.76190476, 0.77777778, 0.79365079, 0.80952381, 0.82539683,
        0.84126984, 0.85714286, 0.87301587],
       [0.88888889, 0.9047619 , 0.92063492, 0.93650794, 0.95238095,
        0.96825397, 0.98412698, 1.        ]])

In [2]:
import pandas as pd

In [2]:
pd.Series

pandas.core.series.Series

In [4]:

pd.Series(data=[1,2,3,4],index=['a','b','c','d'])

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
arr=np.random.randn(5,4)

In [3]:
df=pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'],['l','m','n','o'])

In [5]:
df


l         m         n         o
a -0.411092 -2.335301 -0.403447  0.132020
b  1.491099 -1.910350 -0.854389  1.265264
c  0.111717  1.237290  0.309082 -0.177596
d -0.374943 -0.125589  1.474278  0.884490
e  0.524340  1.261369  0.361609  0.817701

In [12]:
df[['l','m']]

l         m
a -0.411092 -2.335301
b  1.491099 -1.910350
c  0.111717  1.237290
d -0.374943 -0.125589
e  0.524340  1.261369

In [13]:
df['new']=df['l']

In [14]:
df

l         m         n         o       new
a -0.411092 -2.335301 -0.403447  0.132020 -0.411092
b  1.491099 -1.910350 -0.854389  1.265264  1.491099
c  0.111717  1.237290  0.309082 -0.177596  0.111717
d -0.374943 -0.125589  1.474278  0.884490 -0.374943
e  0.524340  1.261369  0.361609  0.817701  0.524340

In [16]:
arr

array([[ 0.94924576, -0.24390625,  0.09227197,  0.51651377],
       [ 0.76479937,  0.88556663, -0.65198122, -0.12913497],
       [-0.83438179, -0.35554328, -0.51573122,  0.49877447],
       [-0.24238224, -0.57691671, -0.70528816,  0.02758312],
       [-1.38969956, -0.49534552, -2.33308293,  1.46088078]])

In [17]:
arr[0,1]

-0.24390624961723165

In [20]:
np.random.seed(10)

In [21]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [22]:
np.random.rand(5)

array([0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [23]:
np.random.seed(10)

In [24]:
np.random.rand(5)


array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [25]:
arr=np.random.randn(5,4)

In [26]:
arr

array([[-0.66437971, -0.60555494, -0.65099088,  0.51256776],
       [ 0.26238882, -0.58273165,  1.36842193,  0.05336866],
       [ 1.49057364,  0.75636693,  0.46964093, -0.23396259],
       [ 0.35365794,  1.78370094, -0.35030121, -0.9896496 ],
       [-0.63425417,  1.89876222,  1.99652279, -1.11867153]])

In [27]:
arr>0

array([[False, False, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True, False, False],
       [False,  True,  True, False]])

In [28]:
arr[arr>0]

array([0.51256776, 0.26238882, 1.36842193, 0.05336866, 1.49057364,
       0.75636693, 0.46964093, 0.35365794, 1.78370094, 1.89876222,
       1.99652279])

In [1]:
df=pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'],['l','m','n','o'])

NameError: name 'pd' is not defined

In [20]:
df

l         m         n         o
a  0.149180 -0.752661  0.573806  0.577827
b -0.471586  2.606345 -1.167970  0.332096
c  0.156467  0.962931 -1.052341 -0.401536
d  0.630448 -0.229282 -1.091523  0.943728
e  1.154957 -0.684749 -1.497791  2.013906

In [21]:
df=df[df>0]
df

l         m         n         o
a  0.149180       NaN  0.573806  0.577827
b       NaN  2.606345       NaN  0.332096
c  0.156467  0.962931       NaN       NaN
d  0.630448       NaN       NaN  0.943728
e  1.154957       NaN       NaN  2.013906

In [51]:
#fill na column wise
for i in df:
    df[i].fillna(value=df[i].mean(),inplace=True)
df

l         m         n         o
a  0.469563  0.326922  1.808543  1.642373
b  2.523305  0.347318  1.620209  1.642373
c  0.347951  0.337120  1.620209  2.621153
d  1.113606  0.337120  0.432960  1.642373
e  1.113606  0.337120  2.619125  0.663593

In [42]:
df

l         m         n         o
a  2.180328  0.190467  1.261686  0.417660
b  0.893958  0.047355  1.034369  1.062011
c  1.537143  0.445769  0.807052  2.141805
d  1.537143  0.525637  1.034369  0.937296
e  1.537143  1.019615  1.034369  0.751281

In [73]:
#fill na row wise
for i in df[df.keys()[0]].keys():
    df.loc[i].fillna(value=df.loc[i].mean(),inplace=True)
df

l         m         n         o
a  1.491614  1.248542  0.636503  1.617508
b  0.560518  0.560518  0.560518  0.560518
c  2.050158  0.145774  1.097966  1.097966
d  0.281433  0.281433  0.281433  0.281433
e  0.984862  1.669452  0.984862  0.300273

In [64]:
df[df.keys()[0]].keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [76]:
df.fillna(0)

l         m         n         o
a  0.503024  0.000000  0.000000  0.236102
b  0.697148  0.000000  0.119891  0.763995
c  0.000000  0.022951  0.055434  0.362758
d  0.296851  1.406954  0.220882  0.989914
e  0.000000  0.458384  1.763625  0.000000

In [22]:
df.mean(axis=1)

a    0.433604
b    1.469220
c    0.559699
d    0.787088
e    1.584431
dtype: float64

In [41]:
df.T.fillna(df.mean(axis=1)).T

l         m         n         o
a  0.149180  0.433604  0.573806  0.577827
b  1.469220  2.606345  1.469220  0.332096
c  0.156467  0.962931  0.559699  0.559699
d  0.630448  0.787088  0.787088  0.943728
e  1.154957  1.584431  1.584431  2.013906

In [33]:
df

l         m         n         o
a  0.149180       NaN  0.573806  0.577827
b       NaN  2.606345       NaN  0.332096
c  0.156467  0.962931       NaN       NaN
d  0.630448       NaN       NaN  0.943728
e  1.154957       NaN       NaN  2.013906

In [11]:
df.to_csv('ex.xlsx')

In [9]:
pd.read_csv('ex')

Unnamed: 0         l         m         n         o
0          a  0.419830 -0.070234  0.118837  0.665872
1          b -0.418404 -0.144307 -0.500551 -0.591224
2          c -0.362042 -0.284722 -0.569443  0.431863
3          d -0.750678 -1.081592 -0.717366  2.341669
4          e -0.046653  0.315133  0.884494 -0.512565

In [34]:
df = pd.read_html('https://www.mohfw.gov.in/')

In [35]:
df[0]

Empty DataFrame
Columns: [(S. No., S. No., S. No.), (Name of State / UT, Name of State / UT, Name of State / UT), (Active Cases*, Total, Total), (Active Cases*, Change since yesterday  Change since yesterday, Change since yesterday  Change since yesterday), (Cured/Discharged/Migrated*, Cumulative, Cumulative), (Cured/Discharged/Migrated*, Change since yesterday, Change since yesterday), (Deaths**, Cumulative, Cumulative), (Deaths**, Change since yesterday, Death During Day (a)), (Deaths**, Change since yesterday, Death Reconciled (b)), (Deaths**, Change since yesterday, Total (a+b))]
Index: []

In [3]:
sal = pd.read_csv('Salaries.csv')

/Users/sandeep/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (3,4,5,6,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [78]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [4]:
sal['BasePay'].replace('[a-z]',np.nan,inplace=True,regex=True)
sal['BasePay']=sal['BasePay'].apply(lambda x:float(x) if isinstance(x,str) else x)


In [181]:
for i in sal['BasePay']:
    if type(i)!=float:
        print(i)

In [ ]:

type(sal['BasePay'][0])

In [5]:
sal['BasePay'].mean()

66325.44884050643

In [6]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [196]:
row=sal[sal['EmployeeName']=='JOSEPH DRISCOLL']
row['TotalPay']+row['Benefits']

24    NaN
dtype: object

In [203]:
x=sal.groupby('Year')['BasePay'].mean()[:3]

In [204]:
x

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
Name: BasePay, dtype: float64

In [214]:
sal.groupby('JobTitle')['JobTitle'].count().sort_values(ascending=False)[:5]

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [257]:
# sal['JobTitle'].compare
result = sal['JobTitle'].str.contains(pat = 'Chief',case=False)
sal.loc[result]['JobTitle'].count()

627

In [252]:
sal[sal['JobTitle'].str.contains('chief',case=False) == True]['JobTitle'].count()

627

In [253]:
def chief_string(title):
    if 'chief' in title.lower():
        return True
    else:
        return False

In [254]:
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

627

In [44]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts()==1)

202

In [54]:
sal['title_len']=sal['JobTitle'].apply(len)
sal[['title_len','TotalPayBenefits']].corr()

title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000